---
- name: Copy files to /etc/skel
  ansible.builtin.copy:
    src: etc/skel/{{ item }}
    dest: /etc/skel
    mode: '0755'
    owner: root
    group: root
  with_items:
    - .bashrc
    - .screenrc

- name: Copy scripts
  ansible.builtin.copy:
    src: usr/local/bin/{{ item }}
    dest: /usr/local/bin
    mode: '0755'
    owner: root
    group: root
  with_items:
    - screen-mem-usage

- name: Copy bashrc to /root
  ansible.builtin.copy:
    src: root/{{ item }}
    dest: /root/.bashrc
    mode: '0755'
    owner: root
    group: root
  with_items:
    - .bashrc

- name: Check existing users
  ansible.builtin.command: ls -1 /home
  changed_when: false
  register: users

- name: Copy files for existing users
  ansible.builtin.copy:
    src: etc/skel/{{ item.0 }}
    dest: /home/{{ item.1 }}
    mode: '0755'
    owner: "{{ item.1 }}"
    group: "{{ item.1 }}"
  with_nested:
    - [ '.bashrc', '.screenrc' ]
    - '{{ users.stdout_lines }}'
